// src/components/stars/Stars.tsx
import { FunctionComponent } from "react";
import Star from "./Star";

const Stars: FunctionComponent<{
  level: number;
  count?: number;
  size?: number;
}> = ({ level, count = 5, size }) => {
  return (
    <div className="flex items-center">
      {[...Array(count)].map((_, i) => (
        <Star
          size={size}
          key={i}
          level={Math.min(Math.max(level * count - i, 0), 1)}
        />
      ))}
    </div>
  );
};

export default Stars;

// src/lib/rating/Stars.svelte
<script lang="ts">
	import Star from "./Star.svelte";

	export let total = 5;
	export let rating = 0;
	export let interactive = false;

	function onStarClick(n: number) {
		if (interactive) {
			rating = n + 1;
		}
	}
</script>

<div class="stars">
	{#each new Array(total) as _, i}
		<Star
			{interactive}
			percentage={Math.min(Math.max(rating - i, 0), 1)}
			on:click={() => onStarClick(i)}
		/>
	{/each}
</div>

<style lang="scss">
	.stars {
		display: flex;
	}
</style>
