// src/components/auth/GoogleLoginButton.tsx
"use client";

import { useEffect, useRef } from "react";
import { useGoogle } from "./GoogleContext";

export default function GoogleLoginButton() {
  const container = useRef<HTMLDivElement>(null);
  const { initialized } = useGoogle();

  useEffect(() => {
    if (!initialized || !container.current) return;
    google.accounts.id.renderButton(container.current, {
      type: "standard",
      size: "large",
      text: "continue_with",
    });
  }, [initialized]);

  return <div ref={container} />;
}

// src/lib/auth/GoogleLoginButton.svelte
<script lang="ts">
	import { onMount } from "svelte";

	let container: HTMLDivElement;

	onMount(() => {
		google.accounts.id.renderButton(container, {
			type: "standard",
			size: "large",
			text: "continue_with"
		});
	});
</script>

<div bind:this={container} />

<style>
	div {
		margin-block: 1rem;
	}
</style>
