// src/components/Header.tsx
"use client";

import { FunctionComponent, useEffect, useState } from "react";
import { Dialog } from "@headlessui/react";
import { Menu, X } from "react-feather";
import Link from "next/link";
import BigSearch from "./oden/BigSearch";
import { useAuth } from "@/lib/auth/context";
import Logo from "./Logo";
import { usePathname } from "next/navigation";
import Spinner from "./Spinner";
import { useAccount } from "@/lib/auth/hooks";

const LogoLink: FunctionComponent = () => (
  <Link href="/" className="-m-1.5 p-1.5">
    <Logo className="h-6" />
  </Link>
);

export default function Header() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const { status } = useAuth();
  const { data: account } = useAccount();
  const pathname = usePathname();

  useEffect(() => {
    setMobileMenuOpen(false);
  }, [pathname]);

  return (
    <header className="bg-white">
      <nav
        className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-8"
        aria-label="Global"
      >
        <div className="flex">
          <LogoLink />
        </div>
        <BigSearch className="mx-4 grow lg:mx-12" />
        <div className="flex lg:hidden">
          <button
            type="button"
            className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
            onClick={() => setMobileMenuOpen(true)}
          >
            <span className="sr-only">Öppna huvudmenyn</span>
            <Menu className="h-6 w-6" aria-hidden="true" />
          </button>
        </div>
        <div className="hidden items-center text-sm font-semibold leading-6 text-gray-900 lg:flex lg:gap-x-12">
          <Link href="/schema">Schema</Link>
          {status !== "unauthenticated" && !account ? (
            <Spinner />
          ) : (
            <Link
              href={status === "authenticated" ? "/konto" : "/login"}
              className="text-sm font-semibold leading-6 text-gray-900"
            >
              {account ? (
                account.full_name
              ) : (
                <>
                  Logga in <span aria-hidden="true">-&gt;</span>
                </>
              )}
            </Link>
          )}
        </div>
      </nav>
      <Dialog
        as="div"
        className="lg:hidden"
        open={mobileMenuOpen}
        onClose={setMobileMenuOpen}
      >
        <div className="fixed inset-0 z-10" />
        <Dialog.Panel className="fixed inset-y-0 right-0 z-10 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
          <div className="flex items-center justify-between">
            <LogoLink />

            <button
              type="button"
              className="-m-2.5 rounded-md p-2.5 text-gray-700"
              onClick={() => setMobileMenuOpen(false)}
            >
              <span className="sr-only">Close menu</span>
              <X className="h-6 w-6" aria-hidden="true" />
            </button>
          </div>
          <div className="mt-6 flow-root">
            <div className="-my-6 divide-y divide-gray-500/10">
              <div className="space-y-2 py-6">
                <Link
                  href="/schema"
                  className="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50"
                >
                  Schema
                </Link>
              </div>
              <div className="py-6">
                <Link
                  href={status === "authenticated" ? "/konto" : "/login"}
                  className="-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50"
                >
                  {account ? (
                    account.full_name
                  ) : (
                    <>
                      Logga in <span aria-hidden="true">-&gt;</span>
                    </>
                  )}
                </Link>
              </div>
            </div>
          </div>
        </Dialog.Panel>
      </Dialog>
    </header>
  );
}

// src/lib/header/Header.svelte
<script lang="ts">
	import { browser } from "$app/environment";
	import { beforeNavigate } from "$app/navigation";
	import { page } from "$app/stores";
	import Search from "$lib/search/Search.svelte";
	import { MenuIcon } from "svelte-feather-icons";
	import { authenticated, authenticating, user } from "../auth";
	import Button from "../Button.svelte";
	import Drawer from "./Drawer.svelte";
	import Skeleton from "../Skeleton.svelte";
	import Logo from "./Logo.svelte";

	let drawerOpen = false;

	beforeNavigate(() => {
		drawerOpen = false;
	});
</script>

<header>
	<div class="container">
		<a href="/" class="logo">
			<Logo />
		</a>
		<Search />
		<button class="toggle" on:click={() => (drawerOpen = !drawerOpen)}>
			<MenuIcon />
		</button>
		<nav>
			<ul>
				<li>
					<a href="/schedule">Schema</a>
				</li>
				<hr />
				{#if browser && !$authenticating}
					{#if $authenticated}
						<li>
							<a href="/account">
								{#if $user?.full_name}
									{$user?.full_name}
								{:else}
									Konto
								{/if}
							</a>
						</li>
					{:else}
						<li><Button href={`/login?next=${$page.url.pathname}`}>Logga in</Button></li>
					{/if}
				{:else}
					<Skeleton width="12rem" height="3rem" />
				{/if}
			</ul>
		</nav>
	</div>
</header>

<Drawer open={drawerOpen} onClose={() => (drawerOpen = false)} />

<style lang="scss">
	header {
		display: flex;
		height: var(--header-height);
		background-color: var(--surface0);
		border-bottom: 1px solid var(--outline);
		box-sizing: border-box;
		padding-inline: var(--page-gutter);
	}

	.container {
		max-width: var(--content-width);
		margin: 0 auto;
		display: flex;
		width: 100%;
		align-items: center;
		justify-content: space-between;
		gap: 0.5rem;

		@media (min-width: 480px) {
			gap: 1rem;
		}
	}

	.logo {
		flex: 0 0 1.5rem;
		display: flex;
		color: var(--text0);

		:global(svg) {
			fill: currentColor;
		}
	}

	nav {
		display: none;
	}

	.toggle {
		--size: 1.5rem;

		all: unset;
		display: flex;
		align-items: center;
		justify-content: center;
		cursor: pointer;
		width: var(--size);
		height: var(--size);
		flex: 0 0 var(--size);

		&:focus {
			outline: var(--theme-hover) solid 2px;
		}
	}

	nav,
	.toggle {
		margin-inline-start: auto;
	}

	@media (min-width: 768px) {
		.toggle {
			display: none;
		}

		nav {
			display: block;
		}
	}

	ul {
		display: flex;
		list-style: none;
		margin: 0;
		padding: 0;
		align-items: center;
		gap: 1rem;
	}

	ul a {
		color: var(--text0-muted);
		text-decoration: none;
		font: 500 0.875rem/1 var(--font-sans);
		transition: color 0.1s;

		&:hover {
			color: var(--text0);
		}
	}

	hr {
		block-size: 1.25rem;
		inline-size: 1px;
		border: none;
		background-color: var(--outline);
		margin: 0;
	}
</style>
